/**
 * Sellify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Int32ValueDiff } from './int32-value-diff.model';
import { IncomeStatsItem } from './income-stats-item.model';
import { DecimalValueDiff } from './decimal-value-diff.model';


export interface GeneralAnalytics { 
    aggregatedAt?: string;
    totalRevenue?: DecimalValueDiff;
    totalOrders?: Int32ValueDiff;
    totalCustomers?: Int32ValueDiff;
    visitorsCount?: Int32ValueDiff;
    income?: Array<IncomeStatsItem> | null;
}

