/**
 * Sellify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderStatus } from './order-status.model';


export interface PurchasedProductData { 
    orderId?: string;
    productId?: number;
    price?: number;
    title?: string | null;
    quantity?: number;
    paidAt?: string;
    orderStatus?: OrderStatus;
}

