/**
 * Sellify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IBinaryData } from './i-binary-data.model';
import { ProductType } from './product-type.model';
import { ProductAttribute } from './product-attribute.model';


export interface SaveProductCommand { 
    id?: number;
    sku?: string | null;
    title?: string | null;
    content?: string | null;
    excerpt?: string | null;
    stock?: number;
    type?: ProductType;
    price?: number;
    categoryId?: number;
    attributes?: Array<ProductAttribute> | null;
    picture?: string | null;
    uploadedPicture?: IBinaryData;
}

