version: '3.8'

services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - ./data/psql/db:/var/lib/postgresql/data
      - ./data/psql/dumps:/psql_dumps
    environment:
      POSTGRES_USER: sellify
      POSTGRES_PASSWORD: sellify
      POSTGRES_DB: sellify

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - ./data/rabbitmq/etc/:/etc/rabbitmq/
      - ./data/rabbitmq/data/:/var/lib/rabbitmq/
      - ./data/rabbitmq/logs/:/var/log/rabbitmq/
#    environment:
#      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
#      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
#      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672